# configs/dataset/cub200.toml
[dataset]
name = "CUB-200"
root = "./data/CUB_200_2011"
num_classes = 200
train_transform = [
    ["RandomResizedCrop", { size = 224 }],
    ["RandomHorizontalFlip"],
    ["ToTensor"],
    ["Normalize", { mean = [0.485, 0.456, 0.406], std = [0.229, 0.224, 0.225] }]
]
test_transform = [
    ["Resize", { size = 256 }],
    ["CenterCrop", { size = 224 }],
    ["ToTensor"],
    ["Normalize", { mean = [0.485, 0.456, 0.406], std = [0.229, 0.224, 0.225] }]
]
