# configs/training/train_20240102_base.toml
[training]
run_name = "test"
output_dir = "./results/base_20240102"
num_train_epochs = 400
per_device_train_batch_size = 32
per_device_eval_batch_size = 100
learning_rate = 1e-6
weight_decay = 0.01
warmup_steps = 500
warmup_ratio = 0.1
logging_dir = "./logs"
logging_steps = 1
evaluation_strategy = "epoch"
save_strategy = "epoch"
save_total_limit = 5
load_best_model_at_end = true
metric_for_best_model = "accuracy"
dataloader_prefetch_factor = 4
dataloader_num_workers=8
# 4流畅 40有点卡

[early_stopping]
patience = 10
threshold = 0.01

[wandb]
project = "CUB-200-Classification"
run_name = "ResNet50-base"

[transform]
train_transform = [
    "RandomResizedCrop(224)",
    "RandomHorizontalFlip()",
    "ToTensor()",
#    "Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])"
]

test_transform = [
    "Resize(256)",
    "CenterCrop(224)",
    "ToTensor()",
#    "Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])"
]
