# train_20250102050700_base.toml
[training]
run_name = "test"
output_dir = "./results/base_20240102"
num_train_epochs = 4000
per_device_train_batch_size = 200
per_device_eval_batch_size = 100
learning_rate = 0.001
weight_decay = 0.01
warmup_steps = 500
warmup_ratio = 0.1
logging_dir = "./logs"
logging_steps = 1
evaluation_strategy = "epoch"
save_strategy = "epoch"
save_total_limit = 5
load_best_model_at_end = true
metric_for_best_model = "accuracy"
dataloader_prefetch_factor = 2
dataloader_num_workers=5
# 4流畅 40有点卡

[early_stopping]
patience = 100
threshold = 0.01

[wandb]
project = "CUB-200-Classification"
run_name = "ResNet50-base"

[transform]
train_transform = [
    "RandomResizedCrop(224)",
    "RandomHorizontalFlip(p=0.5)",
    "ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2)",
    "ToTensor()",
    "Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])",  # 添加逗号
    "RandomRotation(degrees=10)",
    "RandomErasing(p=0.2)",
    "RandAugment(num_ops=2, magnitude=7)"  # 删除最后一行的逗号
]  # 确保有结束的方括号

test_transform = [
    "Resize(256)",
    "CenterCrop(224)",
    "ToTensor()",
    "Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])"
]


